version: '2'
services:
  core_db:
    image: postgres
  task_db:
    image: postgres
  core:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      CREATE_TASKS: 'True'
    depends_on:
      - core_db
  task:
    build: ../task-service
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../task-service:/code
    ports:
      - "8001:8000"
    depends_on:
      - task_db
  nginx:
    build:
      context: .
      dockerfile: config/dev/Dockerfile_nginx
    ports:
      - "8080:80"
    depends_on:
      - core
